python:
   version: 3.5
   install:
      - requirements: docs/requirements.txt
      - method: pip
        path: .
        extra_requirements: docs
      - method: setuptools
   system_packages: true