tmp:
    seq-sim:
        - a
        - uniprot:
            - a
        - tair:
            - a
    domain:
        - iprs:
            - a
    mixed-meth:
        - preprocess:
            - fa:
                - a
            - blast:
                - temp:
                    # - fa:
                    #     - a
                    # - blast:
                    #     - a
        - argot2.5:
            - blast:
                - a
            - hmmer:
                - a
            - results:
                - a
        - pannzer:
            - blast:
                - a
            - results:
                - a
            - conf:
                - a
log:
  - a
gaf:
  - raw:
    - a
  - non_red:
    - a
  - agg:
    - a
  - uniq:
    - a
  - mixed-method:
    - a
input:
    - a
