#Input section 
input:
  #input fasta file name
  fasta: test.fa
  # output file basename
  basename: test
  #input NCBI taxonomy id
  taxon: "4577"
  # Name of the species
  species: "Zea mays"
  # Email is mandatory
  email: 
  #Number of CPUs used for tools
  cpus: 4