#Input section
input:
  #input fasta file name
  fasta: test.fa
  # output file basename
  basename: test 
  #input NCBI taxonomy id
  taxon: "4577"
  # Name of the species
  species: "Zea mays"
  # Email is mandatory
  email: 
  #Number of CPUs used for tools
  cpus: 4

# data section is all the customizable options.
# It is only intended for development purposes.
# Do not change things if you have not looked at the code
data:
  #Settings for Sequence Similarity section
  seq-sim:
    #Settings for TAIR RBH Analysis
    TAIR:
      metadata:
        species:    arabidopsis
    #Settings for UniProt RBH Analysis
    uniprot:
      #selecting the top 10 plant species
      cleaning:
        sel_tax: ['15368', '29760', '3055', '3218', '3694', '3702', '3847', '39947', '4081', '4558']
        # Extra taxa that should be omitted
        omit_tax: ['4577']
      metadata:
        species:    uniprot
  #Domain presence settings which is essentially metadata for interproscan
  domain:
    tool:
        name:       Interproscan5
  #Settings for Mixed-method or CAFA tools
  mixed-method:
      #Preprocessing is an important step of the tools, and the one which takes time. 
    preprocess:
      #The input fasta has to be split for every 10K sequences to use the argot2.5 batch system
      num_seqs: '10000'
      #Blast options to tweak UniProt blast speed and sensitivity
      blast_opts: ["-evalue","10e-10"] 
    argot2:
      #Score thresholds to select annotaitons from Argot2 results
      score_th:
        P: 0.15 
        C: 0.05
        F: 0.15
    pannzer:
      #Score thresholds to select annotaitons from PANNZER results
      score_th:
        P: 0.4
        C: 0.2
        F: 0.55
  # TODO
  gaf:
    raw_dir:          gaf/raw
    non_red_dir:      gaf/non_red
    agg_dir:          gaf/agg
    uniq_dir:         gaf/uniq
    mixed_method_dir: gaf/mixed-method
  # Section for Gene ontology settings.
  go:
    # Gene ontology obo file location which has to be within a directory 
    # that is bound by singularity 
    obo: data/data/go/go.obo 
    # The evidence does that will be ommited when inheriting 
    # between GO annotations of species
    evidence_codes:
      omitted:
      - IEA
      - ND
      - NAS
# Settings for the software used in GOMAP 
software:
  
  blast:
    # Can bind a directory and change the blast executable used
    bin:            data/software/blast-2.6.0+/bin
    # Min evalue cutoff. Has big impact on the results
    evalue:         10e-10
    # Additional BLASTP paramters
    opt_params: ["-max_target_seqs", '10']
  iprs:
    # Can bind a directory and change the iprs and different IPRS can be used
    path:           data/software/interproscan-5.25-64.0
    # Additional interproscan paramters
    options: []
  pannzer:
    # Connection parameters to to PANNZER database
    database:
      SQL_DB: pannzer
      SQL_DB_PASSWORD: ""
      SQL_DB_USER: pannzer
      SQL_DB_HOST: localhost
      SQL_DB_PORT: ""
    # change the path to PANNZER if that is bound as a different path
    path: data/software/PANNZER
    # The template can be changed to accomodate other species
    conf_template: template.conf

# The settings for logging from the pipeline
logging:
  format:           "%(levelname)s [%(asctime)s] %(message)s"
  formatTime:       "%Y-%m-%d %H:%M"
  level:            DEBUG










